# Generated by Django 3.2.5 on 2021-07-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespost',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
