# Generated by Django 3.2.5 on 2021-08-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210801_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlespost',
            old_name='culumn',
            new_name='column',
        ),
    ]
