# Generated by Django 3.2.5 on 2021-08-02 13:40

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_articlespost_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article/%Y%m%d'),
        ),
    ]
