# Generated by Django 3.2.5 on 2021-08-03 09:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articlespost_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespost',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
