# Generated by Django 3.2.5 on 2021-08-06 06:22

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_articlespost_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='article/avatar/%Y%m%d'),
        ),
    ]
