# Generated by Django 3.2.5 on 2021-08-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_articlespost_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
